### PR TITLE
Fixed link to 'Building an ISO' section

### PR DESCRIPTION
**Pull request by YasminBeatriz**
Added an '.md' at the end of BUILDING_AN_ISO at line 106.

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by ghost** [comment]
Thanks for noticing that!
We usually write commit messages using the imperative mood: "Fix link to 'Building an ISO' section"
But don't worry, that's a minor point.
There's a nice guide for writing commit messages here: https://chris.beams.io/posts/git-commit/

**Comment by YasminBeatriz** [comment]
Thank you for this tip!

**Pull request merged**
