### PR TITLE
Support to CentOS major release

### PR DESCRIPTION
**Pull request by lisibann**
This patch modifies config files, directories and scripts to use just CentOS major release (currently, only CentOS 7).

Refer to 'How does CentOS versioning work?'
https://wiki.centos.org/FAQ/General#head-dcca41e9a3d5ac4c6d900a991990fd11930867d6

### CODE REVIEW

**Comment by fabianorosas** [comment]
add to whitelist

**Comment by fabianorosas** [comment]
start tests

**Comment by farosas** [comment]
start build

**Comment by farosas** [comment]
~Build failed because the build nodes still have CentOS 7.2 in them. I'll see what I can do about that.~

Spoke too soon. The issue here is that this patch needs to be in sync with open-power-host-os/versions#84 .

**Review by ghost — APPROVED** [review]

**Review by farosas — APPROVED** [review]

**Pull request merged**
