### PR TITLE
Do not remove build dependencies

### PR DESCRIPTION
**Pull request by mopsfelder**
Do not remove build dependencies and let them in the `result` directory.
- 475f01e Remove unused clean_build_dependencies()
- cd3a3b8 Do not call clean_build_dependencies()

### CODE REVIEW

**Comment by maurorodrigues** [comment]
Can one of the admins verify this patch?

**Comment by maurorodrigues** [comment]
test_plz

**Review by ghost — APPROVED** [review]
I'll wait for build completion and merge this before today's weekly build.

**Comment by ghost** [comment]
Fix #87

**Pull request merged**
