### PR TITLE
Fix duplicated dependencies

### LINKED ISSUE #71: Build dependency removal fails when mentioned twice
Build dep clean up fails when it's a dep for two or more packages cause it's already removed in a previous clean up step for another package. Happened in open-power-host-os/versions#22.

### PR DESCRIPTION
**Pull request by ghost**
When a package is a dependency to multiple others, the build system used to build clone and build it multiple times, what led to a waste of time. When trying to remove the resulting package (in the case of a build dependency) for the second time, the build script failed.
This fixes those issues by disallowing the creation of multiple instances of the same package.

Closes #71

### CODE REVIEW

**Comment by olavphibm** [comment]
test_plz

**Comment by maurorodrigues** [comment]
Can one of the admins verify this patch?

**Comment by olavphibm** [comment]
test_plz

**Comment by olavphibm** [comment]
test_plz

**Comment by olavphibm** [comment]
test_plz

**Pull request merged**
